Interfaz/Controllers/BodegasController.cs
using Dominio.FormulariosAdministracion;
using Dominio.Modelos;
using Dominio.Recursos;
using Infraestructura.CRUD;
using System;
using System.Web.Mvc;

namespace Interfaz.Controllers
{
    public class BodegasController : Controller
    {
        private readonly BDConsultar _BDConsultar = new BDConsultar();
        private readonly BDBodegas _BDBodegas = new BDBodegas();
        private readonly Bodegas _Bodegas = new Bodegas();
        private readonly Combos _Combos = new Combos();


        public ActionResult Index()
        {
            if (Session["Perfil"] == null)
            {
                return RedirectToAction("Index", "Login");
            }

            if ((int)Session["Perfil"] == 2)
            {
                return View(_Bodegas.Consultar());
            }

            return RedirectToAction("Index", "Login");
        }

        public ActionResult Create()
        {
            if (Session["Perfil"] == null)
            {
                return RedirectToAction("Index", "Login");
            }

            if ((int)Session["Perfil"] == 2)
            {
                ViewBag.ListadoBodegas = _Combos.ObtenerBodegas("Sp_ListadoBodegas_ERP");
                return View("Create");
            }

            return RedirectToAction("Index", "Login");
        }

        [HttpPost]
        public ActionResult Create(ModeloBodega Modelo)
        {
            var Bodega = Modelo.IdBodega.Split('-');

            if (_Bodegas.ValidarBodega(Bodega[0]) == "EXISTE")
            {
                ViewBag.ListadoBodegas = _Combos.ObtenerBodegas("Sp_ListadoBodegas_ERP", Bodega[0]);
                ViewData["Error"] = "EL ID DE LA BODEGA YA EXISTE...";
                return View(Modelo);
            }

            _Bodegas.Insertar(Modelo);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int RowId)
        {
            if (Session["Perfil"] == null)
            {
                return RedirectToAction("Index", "Login");
            }

            if ((int)Session["Perfil"] == 2)
            {
                LlenarCombos(RowId);
                return View(_Bodegas.EnviarModelo(RowId));
            }
            return RedirectToAction("Index", "Login");
        }

        [HttpPost]
        public ActionResult Edit(ModeloBodega Modelo)
        {
            _Bodegas.Actualizar(Modelo);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int RowId)
        {
            if (Session["Perfil"] == null)
            {
                return RedirectToAction("Index", "Login");
            }

            if ((int)Session["Perfil"] == 2)
            {
                LlenarCombos(RowId);
                return View(_Bodegas.EnviarModelo(RowId));
            }
            return RedirectToAction("Index", "Login");
        }

        [HttpPost]
        public ActionResult Delete(string RowId)
        {
            _Bodegas.Eliminar(Convert.ToInt32(RowId));
            return Json("La bodega ha sido eliminada.", JsonRequestBehavior.AllowGet);
        }

        public void LlenarCombos(int RowId)
        {
            ViewBag.ListadoOrden = _Combos.ObtenerOrden("Sp_ListadoBodegas", RowId.ToString());
        }
    }
}

Interfaz/Views/Bodegas/Create.cshtml
@model Dominio.Modelos.ModeloBodega

@using System.Data
@using Newtonsoft.Json;

@{
    DataSet DatosImportantes = JsonConvert.DeserializeObject<DataSet>(Session["DatosImportantes"].ToString());
    string Fondo = DatosImportantes.Tables[0].Rows[0]["EP_ColorFondoCentral"].ToString();

    if (DatosImportantes.Tables[0].Rows[0]["EP_UrlFondo"].ToString() != string.Empty)
    {
        Fondo = "background-image:url('" + DatosImportantes.Tables[0].Rows[0]["EP_UrlFondo"].ToString() + "'); background-size: cover";
    }
}

@using (Html.BeginForm())
{
    <fieldset>
        <div class="main-panel">
            <div class="content">
                <div class="card">
                    <div class="card-body" style="@Fondo">
                        <div class="tab-content mt-2 mb-3" id="pills-with-icon-tabContent">
                            <div class="tab-pane fade show active" id="Crear-Usuarios" role="tabpanel" aria-labelledby="pills-home-tab-icon">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <div class="card">
                                            <div class="card-header">
                                                <div class="card-title">Adicionar Bodegas</div>
                                                <a style="color:red">@ViewData["Error"]</a>
                                            </div>
                                            <div class="card-body">
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <label>ID Bodega</label>

                                                        <select id="IdBodega" name="IdBodega" class="form-control" required="required">
                                                            @foreach (var listItem in (List<SelectListItem>)ViewBag.ListadoBodegas)
                                                            {
                                                                <option value="@listItem.Value" @(listItem.Selected ? "selected" : "")>
                                                                    @listItem.Text
                                                                </option>
                                                            }
                                                        </select>
                                                    </div>

                                                    <div class="col-md-6">
                                                        <label>Correo</label>
                                                        @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control", required = "required", @PlaceHolder = "Ingresar Correo" }, })
                                                    </div>

                                                </div>
                                            </div>
                                            <div class="card-action">
                                                <input id="BtnRegistrarUsuario" style="@DatosImportantes.Tables[0].Rows[0]["EP_ColorBotonInsertar"].ToString()" type="submit" class="btn btn-primary" value="Crear" />
                                                <input type="button" style="@DatosImportantes.Tables[0].Rows[0]["EP_ColorBotonRegresar"].ToString()" class="btn btn-danger" value="Regresar" onclick="location.href='@Url.Action("Index", "Bodegas")'" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <footer class="footer">
                <div class="container-fluid">
                    <div class="copyright ml-auto">
                        2019, Hecho <i class="fa fa-helicopter"></i> Por <a href="http://generictransfer.com/">Interfaces Y Soluciones</a>
                    </div>
                </div>
            </footer>
        </div>

        <script src="~/Content/assets/js/core/jquery.3.2.1.min.js"></script>
        <script src="~/Content/assets/js/core/popper.min.js"></script>
        <script src="~/Content/assets/js/core/bootstrap.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
        <script src="~/Content/assets/js/plugin/chart.js/chart.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js"></script>
        <script src="~/Content/assets/js/plugin/chart-circle/circles.min.js"></script>
        <script src="~/Content/assets/js/plugin/datatables/datatables.min.js"></script>
        <script src="~/Content/assets/js/plugin/jqvmap/jquery.vmap.min.js"></script>
        <script src="~/Content/assets/js/plugin/jqvmap/maps/jquery.vmap.world.js"></script>
        <script src="~/Content/assets/js/plugin/sweetalert/sweetalert.min.js"></script>
        <script src="~/Content/assets/js/atlantis.min.js"></script>
        <script src="~/Content/assets/js/setting-demo.js"></script>
        <script src="~/Content/assets/js/demo.js"></script>
    </fieldset>

    <script src="~/Content/assets/js/plugin/webfont/webfont.min.js"></script>
    <script>
        WebFont.load({
            google: { "families": ["Lato:300,400,700,900"] },
            custom: { "families": ["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"], urls: ['../../assets/css/fonts.min.css'] },
            active: function () {
                sessionStorage.fonts = true;
            }
        });
    </script>

}

Interfaz/Views/Bodegas/Delete.cshtml
@model Dominio.Modelos.ModeloBodega

@using System.Data
@using Newtonsoft.Json;

@{
    DataSet DatosImportantes = JsonConvert.DeserializeObject<DataSet>(Session["DatosImportantes"].ToString());
    string Fondo = DatosImportantes.Tables[0].Rows[0]["EP_ColorFondoCentral"].ToString();

    if (DatosImportantes.Tables[0].Rows[0]["EP_UrlFondo"].ToString() != string.Empty)
    {
        Fondo = "background-image:url('" + DatosImportantes.Tables[0].Rows[0]["EP_UrlFondo"].ToString() + "'); background-size: cover";
    }
}

@using (Html.BeginForm())
{
    <fieldset>
        <div class="main-panel">
            <div class="content">
                <div class="card">
                    <div class="card-body" style="@Fondo">
                        <div class="tab-content mt-2 mb-3" id="pills-with-icon-tabContent">
                            <div class="tab-pane fade show active" id="Crear-Usuarios" role="tabpanel" aria-labelledby="pills-home-tab-icon">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <div class="card">
                                            <div class="card-header">
                                                <div class="card-title">Eliminar Bodegas</div>
                                            </div>
                                            <div class="card-body">
                                                @Html.HiddenFor(x => x.RowId)

                                                <div class="row">
                                                    <div class="col-md-2">
                                                        <label>Orden</label>

                                                        <select id="Orden" name="Orden" disabled class="form-control" required="required">
                                                            @foreach (var listItem in (List<SelectListItem>)ViewBag.ListadoOrden)
                                                            {
                                                                <option value="@listItem.Value" @(listItem.Selected ? "selected" : "")>
                                                                    @listItem.Text
                                                                </option>
                                                            }
                                                        </select>
                                                    </div>

                                                    <div class="col-md-4">
                                                        <label>ID Bodega</label>

                                                        @Html.EditorFor(model => model.IdBodega, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled", required = "required", @PlaceHolder = "Ingresar Bodega" }, })
                                                    </div>

                                                    <div class="col-md-4">
                                                        <label>Correo</label>
                                                        @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control", required = "required", @disabled = "disabled", @PlaceHolder = "Ingresar Correo" }, })
                                                    </div>

                                                    <div class="col-md-1">
                                                        <label>Activo</label>
                                                        @Html.EditorFor(model => model.Activo, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                                    </div>
                                                </div>

                                            </div>
                                            <div class="card-action">
                                                <input type="button" style="@DatosImportantes.Tables[0].Rows[0]["EP_ColorBotonEliminar"].ToString(); @DatosImportantes.Tables[0].Rows[0]["EP_ColorTextoBotones"].ToString()" class="btn" value="Eliminar" onclick="Eliminar(@Model.RowId)">
                                                <input type="button" style="@DatosImportantes.Tables[0].Rows[0]["EP_ColorBotonRegresar"].ToString(); @DatosImportantes.Tables[0].Rows[0]["EP_ColorTextoBotones"].ToString()" class="btn" value="Regresar" onclick="location.href='@Url.Action("Index", "Bodegas")'" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <footer class="footer">
                <div class="container-fluid">
                    <div class="copyright ml-auto">
                        2019, Hecho <i class="fa fa-helicopter"></i> Por <a href="http://generictransfer.com/">Interfaces Y Soluciones</a>
                    </div>
                </div>
            </footer>
        </div>

        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
        <script type="text/javascript">
            function Eliminar(RowId) {
                swal({
                    title: "Estás seguro?",
                    text: "Una vez eliminado no podras recuperar la información.",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                })
                    .then((Eliminar) => {
                        if (Eliminar) {
                            $.ajax({
                                type: "POST",
                                data: {
                                    RowId: RowId
                                },
                                url: "/Bodegas/Delete",
                                dataType: "json",
                                success: function (response) {
                                    swal(response, {
                                        icon: "success",
                                    }).then(function () {
                                        window.location.href = "/Bodegas/Index"
                                    });

                                },
                                failure: function (response) {
                                    alert(response.responseText);
                                },
                                error: function (response) {
                                    alert(response.responseText);
                                }
                            });

                        }
                        else {
                            swal("Felicidades, No has eliminado esta bodega!");
                        }
                    });
            }
        </script>

        <script src="~/Content/assets/js/core/jquery.3.2.1.min.js"></script>
        <script src="~/Content/assets/js/core/popper.min.js"></script>
        <script src="~/Content/assets/js/core/bootstrap.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
        <script src="~/Content/assets/js/plugin/chart.js/chart.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js"></script>
        <script src="~/Content/assets/js/plugin/chart-circle/circles.min.js"></script>
        <script src="~/Content/assets/js/plugin/datatables/datatables.min.js"></script>
        <script src="~/Content/assets/js/plugin/jqvmap/jquery.vmap.min.js"></script>
        <script src="~/Content/assets/js/plugin/jqvmap/maps/jquery.vmap.world.js"></script>
        <script src="~/Content/assets/js/plugin/sweetalert/sweetalert.min.js"></script>
        <script src="~/Content/assets/js/atlantis.min.js"></script>
        <script src="~/Content/assets/js/setting-demo.js"></script>
        <script src="~/Content/assets/js/demo.js"></script>
    </fieldset>
}

Interfaz/Views/Bodegas/Edit.cshtml
@model Dominio.Modelos.ModeloBodega

@using System.Data
@using Newtonsoft.Json;

@{
    DataSet DatosImportantes = JsonConvert.DeserializeObject<DataSet>(Session["DatosImportantes"].ToString());
    string Fondo = DatosImportantes.Tables[0].Rows[0]["EP_ColorFondoCentral"].ToString();

    if (DatosImportantes.Tables[0].Rows[0]["EP_UrlFondo"].ToString() != string.Empty)
    {
        Fondo = "background-image:url('" + DatosImportantes.Tables[0].Rows[0]["EP_UrlFondo"].ToString() + "'); background-size: cover";
    }
}

@using (Html.BeginForm())
{
    <fieldset>
        <div class="main-panel">
            <div class="content">
                <div class="card">
                    <div class="card-body" style="@Fondo">
                        <div class="tab-content mt-2 mb-3" id="pills-with-icon-tabContent">
                            <div class="tab-pane fade show active" id="Crear-Usuarios" role="tabpanel" aria-labelledby="pills-home-tab-icon">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <div class="card">
                                            <div class="card-header">
                                                <div class="card-title">Actualizar Bodegas</div>
                                                <a style="color:red">@ViewData["Error"]</a>
                                            </div>
                                            <div class="card-body">
                                                @Html.HiddenFor(x => x.RowId)
                                                @Html.HiddenFor(x => x.IdBodega)

                                                <div class="row">

                                                    <div class="col-md-2">
                                                        <label>Orden</label>

                                                        <select id="Orden" name="Orden" class="form-control" required="required">
                                                            @foreach (var listItem in (List<SelectListItem>)ViewBag.ListadoOrden)
                                                            {
                                                                <option value="@listItem.Value" @(listItem.Selected ? "selected" : "")>
                                                                    @listItem.Text
                                                                </option>
                                                            }
                                                        </select>
                                                    </div>

                                                    <div class="col-md-4">
                                                        <label>ID Bodega</label>

                                                        @Html.EditorFor(model => model.IdBodega, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled", required = "required", @PlaceHolder = "Ingresar Bodega" }, })
                                                    </div>

                                                    <div class="col-md-4">
                                                        <label>Correo</label>
                                                        @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control", required = "required", @PlaceHolder = "Ingresar Correo" }, })
                                                    </div>

                                                    <div class="col-md-1">
                                                        <label>Activo</label>
                                                        @Html.EditorFor(model => model.Activo, new { htmlAttributes = new { @class = "form-control" } })
                                                    </div>

                                                </div>
                                            </div>
                                            <div class="card-action">
                                                <input id="BtnRegistrarUsuario" style="@DatosImportantes.Tables[0].Rows[0]["EP_ColorBotonInsertar"].ToString()" type="submit" class="btn btn-primary" value="Actualizar" />
                                                <input type="button" style="@DatosImportantes.Tables[0].Rows[0]["EP_ColorBotonRegresar"].ToString()" class="btn btn-danger" value="Regresar" onclick="location.href='@Url.Action("Index", "Bodegas")'" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <footer class="footer">
                <div class="container-fluid">
                    <div class="copyright ml-auto">
                        2019, Hecho <i class="fa fa-helicopter"></i> Por <a href="http://generictransfer.com/">Interfaces Y Soluciones</a>
                    </div>
                </div>
            </footer>
        </div>

        <script src="~/Content/assets/js/core/jquery.3.2.1.min.js"></script>
        <script src="~/Content/assets/js/core/popper.min.js"></script>
        <script src="~/Content/assets/js/core/bootstrap.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
        <script src="~/Content/assets/js/plugin/chart.js/chart.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js"></script>
        <script src="~/Content/assets/js/plugin/chart-circle/circles.min.js"></script>
        <script src="~/Content/assets/js/plugin/datatables/datatables.min.js"></script>
        <script src="~/Content/assets/js/plugin/jqvmap/jquery.vmap.min.js"></script>
        <script src="~/Content/assets/js/plugin/jqvmap/maps/jquery.vmap.world.js"></script>
        <script src="~/Content/assets/js/plugin/sweetalert/sweetalert.min.js"></script>
        <script src="~/Content/assets/js/atlantis.min.js"></script>
        <script src="~/Content/assets/js/setting-demo.js"></script>
        <script src="~/Content/assets/js/demo.js"></script>
    </fieldset>

    <script src="~/Content/assets/js/plugin/webfont/webfont.min.js"></script>
    <script>
        WebFont.load({
            google: { "families": ["Lato:300,400,700,900"] },
            custom: { "families": ["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"], urls: ['../../assets/css/fonts.min.css'] },
            active: function () {
                sessionStorage.fonts = true;
            }
        });
    </script>

}